const $=s=>document.querySelector(s);const notes=$("#notes"),tasksEl=$("#tasks"),taskDialog=$("#taskDialog"),taskInput=$("#taskInput");
let tasks=JSON.parse(localStorage.getItem("aph_tasks")||"[]"),favorites=JSON.parse(localStorage.getItem("aph_prompt_favorites")||"[]"),activePrompt=null,favoritesOnly=false;
const save=()=>{localStorage.setItem("aph_tasks",JSON.stringify(tasks));render()};
function render(){tasksEl.innerHTML="";tasks.forEach((t,i)=>{const row=document.createElement("div");row.className=`task ${t.done?"done":""}`;row.innerHTML=`<input type="checkbox" ${t.done?"checked":""} aria-label="Complete task"><span></span><button class="delete" aria-label="Delete task">×</button>`;row.querySelector("span").textContent=t.text;row.querySelector("input").onchange=()=>{tasks[i].done=!tasks[i].done;save()};row.querySelector(".delete").onclick=()=>{tasks.splice(i,1);save()};tasksEl.appendChild(row)});$("#taskCount").textContent=`${tasks.filter(t=>!t.done).length} open task${tasks.filter(t=>!t.done).length===1?"":"s"}`}
$("#addTask").onclick=()=>{taskInput.value="";taskDialog.showModal();taskInput.focus()};$("#taskForm").onsubmit=e=>{e.preventDefault();tasks.unshift({text:taskInput.value.trim(),done:false});taskDialog.close();save()};
document.querySelectorAll(".workflow").forEach(b=>b.onclick=()=>{tasks.unshift({text:b.dataset.template,done:false});save()});
notes.value=localStorage.getItem("aph_notes")||"";notes.oninput=()=>{localStorage.setItem("aph_notes",notes.value);$("#saveStatus").textContent="Saving…";clearTimeout(window.noteTimer);window.noteTimer=setTimeout(()=>$("#saveStatus").textContent="Saved locally",400)};
function copyText(text,button){navigator.clipboard?.writeText(text).then(()=>{const old=button.textContent;button.textContent="Copied ✓";setTimeout(()=>button.textContent=old,1200)}).catch(()=>alert("Copy was not available in this browser."))}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem("aph_prompt_favorites",JSON.stringify(favorites));renderPrompts();if(activePrompt)updateDialogFavorite()}
function renderPrompts(){const q=$("#promptSearch").value.toLowerCase().trim(),cat=$("#promptCategory").value;const filtered=PROMPTS.filter(p=>(cat==='all'||p.category===cat)&&(!favoritesOnly||favorites.includes(p.id))&&(!q||`${p.title} ${p.purpose} ${p.category} ${p.prompt}`.toLowerCase().includes(q)));const el=$("#promptResults");el.innerHTML=filtered.length?filtered.map(p=>`<article class="prompt-card"><div class="prompt-meta"><span>${p.category}</span><button class="star-btn ${favorites.includes(p.id)?'saved':''}" data-fav="${p.id}" title="Favorite">${favorites.includes(p.id)?'★':'☆'}</button></div><h3>${p.title}</h3><p>${p.purpose}</p><button class="open-prompt" data-open="${p.id}">View prompt →</button></article>`).join(""):`<div class="empty-state"><h3>No prompts found</h3><p>Try another keyword, category, or turn off Favorites.</p></div>`;el.querySelectorAll("[data-fav]").forEach(b=>b.onclick=()=>toggleFavorite(Number(b.dataset.fav)));el.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openPrompt(Number(b.dataset.open)))}
function openPrompt(id){activePrompt=PROMPTS.find(p=>p.id===id);if(!activePrompt)return;$("#dialogCategory").textContent=activePrompt.category;$("#dialogTitle").textContent=activePrompt.title;$("#dialogPurpose").textContent=activePrompt.purpose;$("#dialogPrompt").textContent=activePrompt.prompt;$("#dialogTip").textContent=`Tip: ${activePrompt.tip}`;updateDialogFavorite();$("#promptDialog").showModal()}
function updateDialogFavorite(){$("#favoriteDialog").textContent=favorites.includes(activePrompt.id)?"★ Favorited":"☆ Favorite"}
$("#copyDialog").onclick=()=>copyText(activePrompt.prompt,$("#copyDialog"));$("#favoriteDialog").onclick=()=>toggleFavorite(activePrompt.id);$("#closePrompt").onclick=()=>$("#promptDialog").close();
const cats=[...new Set(PROMPTS.map(p=>p.category))].sort();cats.forEach(c=>$("#promptCategory").insertAdjacentHTML("beforeend",`<option value="${c}">${c}</option>`));$("#promptSearch").oninput=renderPrompts;$("#promptCategory").onchange=renderPrompts;$("#favoritesOnly").onclick=()=>{favoritesOnly=!favoritesOnly;$("#favoritesOnly").textContent=favoritesOnly?"★ Favorites":"☆ Favorites";renderPrompts()};
document.querySelectorAll(".nav-btn").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(".nav-btn").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$(btn.dataset.view==='dashboard'?"#dashboardView":"#promptsView").classList.remove("hidden");if(btn.dataset.view==='prompts')renderPrompts()});
$("#focusBtn").onclick=()=>document.body.classList.toggle("focus-mode");$("#today").textContent=new Intl.DateTimeFormat(undefined,{weekday:"long",month:"short",day:"numeric"}).format(new Date());render();renderPrompts();
