const draftKey="aph_document_draft";
let draft=JSON.parse(localStorage.getItem(draftKey)||"null")||{type:"Academic report",title:"",audience:"",purpose:"",outline:"",sourceNotes:"",draft:""};
const d=id=>document.querySelector(id);
const draftSave=()=>{localStorage.setItem(draftKey,JSON.stringify(draft));const s=d("#draftSaveStatus");if(s){s.textContent="Saving…";clearTimeout(window.draftTimer);window.draftTimer=setTimeout(()=>s.textContent="Saved locally",350)}};
function renderDraft(){["type","title","audience","purpose","outline","sourceNotes","draft"].forEach(k=>{const el=d(`#draft-${k}`);if(el)el.value=draft[k]||""});updateDraftSummary()}
function updateDraftSummary(){if(!d("#draftWordCount"))return;const words=(draft.draft.trim().match(/\S+/g)||[]).length;d("#draftWordCount").textContent=`${words} words`;d("#draftProgress").textContent=draft.draft.trim()?"Draft in progress":"Ready to draft"}
["type","title","audience","purpose","outline","sourceNotes","draft"].forEach(k=>d(`#draft-${k}`)?.addEventListener("input",e=>{draft[k]=e.target.value;draftSave();updateDraftSummary()}));
d("#draftCopy")?.addEventListener("click",()=>{const text=`${draft.title||"Untitled document"}\n\nDocument type: ${draft.type}\nAudience: ${draft.audience}\nPurpose: ${draft.purpose}\n\nOUTLINE\n${draft.outline}\n\nSOURCE NOTES\n${draft.sourceNotes}\n\nDRAFT\n${draft.draft}`;navigator.clipboard?.writeText(text).then(()=>{const b=d("#draftCopy"),old=b.textContent;b.textContent="Copied ✓";setTimeout(()=>b.textContent=old,1200)})});
d("#useResearch")?.addEventListener("click",()=>{const r=JSON.parse(localStorage.getItem("aph_research_workspace")||"null");if(!r)return alert("No saved research workspace found yet.");draft.title=draft.title||r.title||"";draft.purpose=draft.purpose||r.question||"";draft.outline=draft.outline||r.objectives||"";draft.sourceNotes=draft.sourceNotes||`${(r.sources||[]).map((s,i)=>`${i+1}. ${s.title}${s.author?` — ${s.author}`:""}${s.url?` — ${s.url}`:""}`).join("\n")}\n\nEvidence:\n${r.notes||""}\n\nFindings:\n${r.findings||""}\n\nSynthesis:\n${r.synthesis||""}`;renderDraft();draftSave()});
d("#clearDraft")?.addEventListener("click",()=>{if(confirm("Clear this document draft?")){draft={type:"Academic report",title:"",audience:"",purpose:"",outline:"",sourceNotes:"",draft:""};draftSave();renderDraft()}});
renderDraft();
