const researchKey="aph_research_workspace";
let research=JSON.parse(localStorage.getItem(researchKey)||"null")||{title:"",question:"",keywords:"",literature:"",objectives:"",sources:[],notes:"",findings:"",synthesis:""};
const researchSave=()=>{localStorage.setItem(researchKey,JSON.stringify(research));const s=document.querySelector("#researchSaveStatus");if(s){s.textContent="Saving…";clearTimeout(window.researchTimer);window.researchTimer=setTimeout(()=>s.textContent="Saved locally",350)}};
const r=id=>document.querySelector(id);function renderResearch(){["title","question","keywords","literature","objectives","notes","findings","synthesis"].forEach(k=>{const el=r(`#research-${k}`);if(el)el.value=research[k]||""});renderSources();refreshResearchSummary()}
function refreshResearchSummary(){if(r("#summaryQuestion"))r("#summaryQuestion").textContent=research.question||"Add your research question.";if(r("#summarySources"))r("#summarySources").textContent=`${research.sources.length} source${research.sources.length===1?'':'s'} captured.`;if(r("#summaryFindings"))r("#summaryFindings").textContent=research.findings||"No findings captured yet."}
function renderSources(){const el=r("#sourceList");if(!el)return;el.innerHTML=research.sources.length?research.sources.map((s,i)=>`<div class="source-item"><div><strong>${escapeHtml(s.title)}</strong><span>${escapeHtml(s.type)}${s.author?` · ${escapeHtml(s.author)}`:""}</span>${s.url?`<a href="${escapeAttr(s.url)}" target="_blank" rel="noopener">Open source ↗</a>`:""}</div><button class="delete" data-source="${i}" aria-label="Delete source">×</button></div>`).join(""):"<p class='empty-inline'>No sources added yet. Capture your first source above.</p>";el.querySelectorAll("[data-source]").forEach(b=>b.onclick=()=>{research.sources.splice(Number(b.dataset.source),1);researchSave();renderSources();refreshResearchSummary()})}
function escapeHtml(v=""){return v.replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]))}function escapeAttr(v=""){return escapeHtml(v).replace(/'/g,"&#39;")}
["title","question","keywords","literature","objectives","notes","findings","synthesis"].forEach(k=>{const el=r(`#research-${k}`);el?.addEventListener("input",()=>{research[k]=el.value;researchSave();refreshResearchSummary()})});
r("#sourceForm")?.addEventListener("submit",e=>{e.preventDefault();const title=r("#sourceTitle").value.trim();if(!title)return;research.sources.push({title,author:r("#sourceAuthor").value.trim(),type:r("#sourceType").value,url:r("#sourceUrl").value.trim()});e.target.reset();researchSave();renderSources();refreshResearchSummary()});
r("#clearResearch")?.addEventListener("click",()=>{if(confirm("Clear this research workspace? This removes its locally saved content.")){research={title:"",question:"",keywords:"",literature:"",objectives:"",sources:[],notes:"",findings:"",synthesis:""};researchSave();renderResearch()}});
r("#researchCopy")?.addEventListener("click",()=>{const text=`RESEARCH PROJECT\n\nTitle: ${research.title}\nResearch question: ${research.question}\nKeywords: ${research.keywords}\n\nLITERATURE REVIEW STRUCTURE\n${research.literature}\n\nObjectives:\n${research.objectives}\n\nSOURCES\n${research.sources.map((s,i)=>`${i+1}. ${s.title}${s.author?` — ${s.author}`:""}${s.url?` — ${s.url}`:""}`).join("\n")}\n\nEVIDENCE / NOTES\n${research.notes}\n\nKEY FINDINGS\n${research.findings}\n\nSYNTHESIS\n${research.synthesis}`;navigator.clipboard?.writeText(text).then(()=>{const b=r("#researchCopy"),old=b.textContent;b.textContent="Copied ✓";setTimeout(()=>b.textContent=old,1200)})});renderResearch();